version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: meu_clube_dbv
      POSTGRES_PASSWORD: secret
    volumes:
      - meuclube_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  meuclube_postgres_data: {}